_BASE_: "../Base-RetinaNet-VOC.yaml"
MODEL:
  WEIGHTS: /home/ubuntu/gfav/repos/detectron2/pretrained_models/RetinaNet/model_final_59f53c.pkl
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (4640, 6327)
  MAX_ITER: 7030
  CHECKPOINT_PERIOD: 800
  IMS_PER_BATCH: 2
  BASE_LR: 0.001 
DATALOADER:
  NUM_WORKERS: 2